### ISSUE TITLE
Logos/Grafik etc

### ISSUE THREAD

**Issue by hmt** [SVWS-NRW/SVWS-UI-Framework#5]
Da das UI-Framework MIT-lizenziert ist, sollten die Grafiken, z.B. das NRW-Logo per Slot vom Client eingefügt werden. M.W. dürfen die Logos nicht beliebig verwendet werden. Ist das richtig? Das gleiche Problem wäre dann natürlich auch beim Client... Abgesehen davon sollte ein Framework keine Logos etc vorab einfügen.

**Comment by FPfotenhauer** [comment]
Das ist korrekt. Momentan ist auf dem Bild ja noch dieses Wasserzeichen.
Wir hatten überlegt, ob wir selber Bilder machen lassen, damit wir daran alle Rechte haben.
Im Client haben wir so Schüler*innen-Default-Bilder, die CC0 Lizenz habe ich aber in einer TXT-Datei dazu gelegt...

**Comment by FPfotenhauer** [comment]
Wir sollten das am Donnerstag auch ansprechen.
Ich versuche auch gerade 2-3 Bilder zu bekommen, an denen wir alle Rechte haben.
